export enum ConversationStage {
  INTRO = 'INTRO',
  BRAINSTORMING = 'BRAINSTORMING',
  SOLUTION = 'SOLUTION',
  CONCLUSION = 'CONCLUSION',
  REFINEMENT = 'REFINEMENT',
  TOPIC_SHIFT = 'TOPIC_SHIFT',
  UNKNOWN = 'UNKNOWN'
}